# .goreleaser.yaml
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/cloudoperators/cloudctl/cmd.Version={{.Version}}
      - -X github.com/cloudoperators/cloudctl/cmd.GitCommit={{.Commit}}
      - -X github.com/cloudoperators/cloudctl/cmd.BuildDate={{.Date}}
    main: .
    binary: cloudctl

archives:
  - formats:
      - tar.gz
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  split: true

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
